### ISSUE TITLE
VirusTotal Positive - 2 Vendors

### ISSUE THREAD

**Issue by C0ldFr1ss0n** [ZiedYT/chats-revenge-public#1]
I hope you do not take offense to this, as it definitely not meant. VirusTotal has two vendors that flag this as viral, Microsoft and Jiangmin. Are they false positives, as the program modifies the monitor, or something else? I see you doing crazy cool stuff on your YouTube, so I don't think you'd risk that, but I always like to be safe. Here is the VirusTotal link: https://www.virustotal.com/gui/file/9ecf4cb31d9cd8dd47647d29365914b7665f9daaef8f97af767b8af20233dbe8?nocache=1

- C0ldFr1ss0n

**Comment by ZiedYT** [comment]
Yeah these are false negatives. On top of messing with the monitor, the tool allows chat to do stuff like block the keyboard, press a key... Which is not something a conventional software should do, so it gets flagged alot.

**Comment by C0ldFr1ss0n** [comment]
Thank you very much for the clarification. Just out of curiosity, is there a page that lists the bit redeems chat has done? Sometimes it's fun to see who did what. :)

**Comment by ZiedYT** [comment]
There is an overlay that shows a text when someone redeems something but no logging feature. It sounds like a good idea, I will add it.
