### ISSUE TITLE
Issues with GUI 

### ISSUE THREAD

**Issue by Lostinthelinks** [ZiedYT/chats-revenge-public#2]
After starting the app the GUI isn't allowing me to switch between Tabs, it just pushes me back to the settings tab.

**Comment by ZiedYT** [comment]
You have to type your channel name, and get your oauth and paste it in the second field.

**Comment by Lostinthelinks** [comment]
Did that, Still doesn't allow changing tabs. Am I missing something when copying and pasting the Oauth

**Comment by ZiedYT** [comment]
does the token field have a red outline?

**Comment by Lostinthelinks** [comment]
Yes even after pasting the OAuth and inputting the channel name

**Comment by Lostinthelinks** [comment]
Think I figured it out. Sorry for the confusion. Just needed to reset and start again. Works correctly now. I appreciate the quick response
