### ISSUE TITLE
Can access only setting tab

### ISSUE THREAD

**Issue by Xeraccoon** [ZiedYT/chats-revenge-public#4]
Hi, i can't access to tab "rewards", "create channel Points" and "configure bits rewards"

Only settings tab are availiable , when i click over other tab im always switched on the default "settings" tab

https://i.imgur.com/Rghpuag.png

im on windows 11

**Comment by ZiedYT** [comment]
Hello. You have to type your channel name not your url

**Comment by Xeraccoon** [comment]
my bad thx, it's good
